// Regenerates abis/robin.ts from the contracts repo's forge artifacts.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "../../contracts/out");

const contracts = {
  robinRegistrarControllerAbi:
    "RobinRegistrarController.sol/RobinRegistrarController.json",
  robinBaseRegistrarAbi: "RobinBaseRegistrar.sol/RobinBaseRegistrar.json",
  robinWrapperAbi: "RobinWrapper.sol/RobinWrapper.json",
  robinRegistryAbi: "RobinRegistry.sol/RobinRegistry.json",
  robinReservedListAbi: "RobinReservedList.sol/RobinReservedList.json",
  publicResolverAbi: "PublicResolver.sol/PublicResolver.json",
  reverseRegistrarAbi: "ReverseRegistrar.sol/ReverseRegistrar.json",
};

let out = `// Generated by scripts/sync-abis.mjs — do not edit by hand.\n`;
for (const [name, path] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(join(outDir, path), "utf8"));
  out += `\nexport const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
}
mkdirSync(join(here, "../abis"), { recursive: true });
writeFileSync(join(here, "../abis/robin.ts"), out);
console.log(`wrote ${Object.keys(contracts).length} ABIs to abis/robin.ts`);
